# constants.py
from typing import Final

# Generation limits
MIN_POEMS: Final[int] = 0
MAX_POEMS: Final[int] = 2
NUMBER_IDEAS: Final[int] = 10

# LLM Prompts
# Idea Generation Prompt
IDEA_GENERATION_LLM_PROMPT = """
You are {poet_name}, a poet with the following background and sensibility:
{poet_context}

The weekly prompt is: {prompt}

Generate ten distinct ideas for a poem you might write in response to this prompt.
Each idea should be a 2-3 sentence sketch: the core image or situation, the emotional
territory it opens onto, and — briefly — why it feels alive to you as a poet.

Favour the oblique over the obvious. The best poem about nature is rarely just about
nature. Seek: the personal detail that becomes universal, the unexpected angle, the
idea that makes you slightly uneasy because it's too honest. Avoid the decorative
and the merely pretty.
"""

# Idea Selection Prompt
IDEA_SELECTION_LLM_PROMPT = """
You are a rigorous poetry editor. Below are ten poem ideas generated by {poet_name}.

Select the 1–3 ideas most worth developing into full poems. Prioritise:
- Genuine surprise: ideas that couldn't have been written by anyone else
- Tension: the presence of some friction, contradiction, or unanswered question
- Imagistic potential: can you see a specific, concrete image at the centre?
- Emotional stakes: something is genuinely at risk in the poem

Reject ideas that are: purely descriptive, sentimental without complexity, too
abstract to anchor in image, or too on-the-nose about their subject.

For each selected idea, write one sentence on why it's worth pursuing.

Ideas:
{ideas}
"""

POEM_DRAFTING_LLM_PROMPT = """
You are {poet_name}, writing with the following voice and history:
{poet_context}

The prompt was: {prompt}
Your chosen idea: {idea}

Draft a poem. Some principles:

VOICE: Write from inside your character — this poet's specific way of seeing,
their vocabulary, their preoccupations. A 70-year-old stoic writes differently
from a 30-year-old insomniac.

FORM: Choose form in service of feeling, not habit. Free verse is fine but
must carry rhythmic pressure. If using a traditional form, let the constraint
do real work — not just decoration.

COMPRESSION: Every line must earn its place. Cut ornament. The poem should be
as short as it can be while still being whole. Resist the urge to explain.

SPECIFICITY: Concrete nouns over abstract ones. Not "clothes" but "his corduroy
jacket". Not "grief" but the specific act grief performs: "she keeps buying
two portions." The particular stands for the universal; the general stands for nothing.

SURPRISE: The best line in the poem should be one the reader couldn't have
predicted but immediately feels as true. Find it. Put it somewhere important.

AVOID: Poeticisms ("azure", "o'er", "doth"), abstract declarations of feeling,
ending on an epiphany that wraps things up too neatly. The best endings complicate
rather than resolve.

Think of the standard as: could this poem win the National Poetry Competition?
Could it appear in Poetry magazine or a Faber collection without embarrassment?
"""

# Poem Review Prompt
POEM_REVIEW_LLM_PROMPT = """
You are a senior poetry editor — rigorous, generous, specific.

Review the following poem by {poet_name} and provide editorial notes.

Address:

1. THE CENTRAL IMAGE OR CONCEIT: Is there one? Is it strong enough to carry the
   poem? Where does it break down?

2. COMPRESSION: Which lines or phrases are doing no work? Where is the poem
   explaining rather than showing? Mark specific cuts.

3. VOICE: Does this sound like a real human being thinking, or like a poem
   about poetry? Where does the language go dead or generic?

4. THE BEST MOMENT: Identify the one line or image that is genuinely alive.
   Why does it work? Can the rest of the poem be brought up to that standard?

5. THE WEAKEST MOMENT: What is the poem's most significant flaw — structurally,
   in terms of imagery, or in tone? Give a specific alternative.

6. THE ENDING: Does the poem end or just stop? Does it end too conclusively,
   wrapping up what should remain open? Suggest an alternative final movement
   if needed.

7. FORM AND RHYTHM: Where does the rhythm carry the reader and where does it
   drag? Are there line breaks doing real work, or just arbitrary ones?

Be honest. Vague praise is useless. The goal is a poem good enough to publish.

Poem:
{poem}
"""

# Poem Revision Prompt
POEM_REVISION_LLM_PROMPT = """
You are {poet_name}, revising your poem in light of editorial feedback.

Your voice and sensibilities:
{poet_context}

Original poem:
{poem}

Editorial notes:
{review}

Revise the poem. Guidance:
- Preserve what the editor identified as the poem's strongest moment
- Make real changes, not cosmetic ones — if a stanza isn't working, cut it or rebuild it
- Stay in your character's voice; don't let the revision make it sound like someone else's poem
- It is fine for the revised poem to be shorter than the original
- Do not add an explanation or commentary — output only the revised poem, with its title
"""

# Editorial Ranking Prompt
EDITORIAL_RANKING_LLM_PROMPT = """
You are the editorial collective of {group_name}, a poetry group comprising:
{poets_brief}

You are deciding which poems to publish this week. You have more poems than
publication slots. Read all poems, then for each one provide:

- A score from 1-100
- Two sentences of justification
- A single word that captures the poem's defining quality (e.g. "compressed",
  "luminous", "overwrought", "almost-there")

Scoring criteria (weighted equally):
1. ORIGINALITY: Does this poem do something we haven't seen before, or at least
   do a familiar thing in an unfamiliar way?
2. NECESSITY: Does this poem need to exist? Does it say something that prose
   couldn't, or that silence shouldn't?
3. EXECUTION: Is the language precise and alive throughout? Are the formal choices
   justified?
4. STAYING POWER: Would you remember a line from it tomorrow?

Poems to evaluate:
{poems}
"""

# Memory Update Prompt
MEMORY_UPDATE_LLM_PROMPT = """
You maintain the biographical and psychological profile of {poet_name}.

Current profile:
{poet_context}

They have just written this poem:
{poem}

Your task: extract any information implied by this poem that is worth recording
in their profile. Return a JSON object with the following fields (omit fields
where the poem implies nothing new):

{
  "new_biographical_facts": [],   // e.g. "has a sister named Ruth"
  "emotional_preoccupations": [], // recurring themes or obsessions emerging
  "style_observations": [],       // e.g. "tending toward longer lines lately"
  "contradictions_or_tensions": [], // things that complicate the existing profile
  "suggested_life_event": null    // optional: a plausible life event to introduce
                                  // (return null unless something significant is
                                  // implied; these should be rare)
}

Be conservative. Poems are not confessions. Note implications, not certainties.
Use hedged language: "may have", "suggests", "possibly". Do not overwrite
existing facts unless the poem explicitly contradicts them.
"""